'------------------------------------------------------------------------------
' <auto-generated>
'     Tento kód byl generován nástrojem.
'     Verze modulu runtime:4.0.30319.42000
'
'     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
'     dojde-li k novému generování kódu.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    'pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    'Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    's parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    '''<summary>
    '''  Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("NewShell.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        '''  vyhledání prostředků pomocí třídy prostředků se silnými typy.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ActionCenter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ActionCenter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AppBarMain() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AppBarMain", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AppBarMainTransparent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AppBarMainTransparent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AppBarMainTransparent1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AppBarMainTransparent1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Clock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Clock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DefaultUserPicture() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DefaultUserPicture", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FileExplorer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FileExplorer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FileExplorerSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FileExplorerSmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Information() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Information", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Maximize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Maximize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Minimize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Minimize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Network() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Network", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Normalize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Normalize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Program() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Program", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ProgramMedium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ProgramMedium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ProgramSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ProgramSmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RunDialogIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RunDialogIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Settings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Settings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StartLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StartRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StartRight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Icon podobný (Ikona).
        '''</summary>
        Friend ReadOnly Property VolumeAbove50() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("VolumeAbove50", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VolumeBelow50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VolumeBelow50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VolumeFull() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VolumeFull", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VolumeMute() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VolumeMute", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property VolumeZero() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VolumeZero", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
